//Package imports (Generated by IntelliJ)
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Arrays;


public class LoginFrame extends JFrame implements ActionListener {
    //Container that holds all the elements
    Container container = getContentPane();
    //Creating instances of elements
    JLabel userLabel = new JLabel("Username");
    JLabel passLabel = new JLabel("Password");
    JTextField userTextField = new JTextField();
    JPasswordField passField = new JPasswordField();
    JButton loginButton = new JButton("Log in");
    JButton resetButton = new JButton("Reset");
    JCheckBox showPassword = new JCheckBox("Show Password");
    JLabel registerLabel = new JLabel("Register New User");
    //Constructor (calling all the other methods)
    LoginFrame() {
        setLayoutManager();
        setLocationAndSize();
        addComponentsToContainer();
        addActionEvent();
    }

    //Setting bounds manually, so don't need a layout manager
    public void setLayoutManager() {
        container.setLayout(null);
    }

    //Setting the bounds for all the elements
    public void setLocationAndSize() {
        //Username elements
        userLabel.setBounds(50,50,100,30);
        userTextField.setBounds(150,50,150,30);
        //Password elements
        passLabel.setBounds(50,100,100,30);
        passField.setBounds(150,100,150,30);
        passField.setEchoChar('*');
        //Other elements
        showPassword.setBounds(150,130,150,30);
        loginButton.setBounds(50,180,100,30);
        resetButton.setBounds(200,180,100,30);
    }

    //Adds all the components to the container
    public void addComponentsToContainer() {
        container.add(userLabel);
        container.add(passLabel);
        container.add(userTextField);
        container.add(passField);
        container.add(loginButton);
        container.add(resetButton);
        container.add(showPassword);
    }

    //Adds event listeners to the necessary elements
    public void addActionEvent() {
        loginButton.addActionListener(this);
        resetButton.addActionListener(this);
        showPassword.addActionListener(this);
    }

    //Controls the actions of the login, reset and show password buttons
    @Override
    public void actionPerformed(ActionEvent actionEvent) {
        //If the event come from the login button...
        if (actionEvent.getSource() == loginButton) {
            String userText;
            String pwdText;
            //Get whatever's inside the username and password fields
            userText = userTextField.getText();
            pwdText = passField.getText();
            try {
                //Checks if the login is correct
                if (UserData.getInstance().isLoginCorrect(userText, pwdText)) {
                    //And displays message (temporary) //TODO change this once developed
                    JOptionPane.showMessageDialog(this, "Correct Login");
                }
                else {
                    //If it's not correct, show error message.
                    JOptionPane.showMessageDialog(this, "Incorrect Login");
                }
            }
            catch (InvalidKeySpecException e) {
                e.printStackTrace();
            }
            catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            }
        }
        //If the event comes from the reset button...
        if (actionEvent.getSource() == resetButton) {
            //Set the text inside the fields to be blank
            userTextField.setText("");
            passField.setText("");
        }
        //If the event comes from the show password button...
        if (actionEvent.getSource() == showPassword) {
            //If the button is selected...
            if (showPassword.isSelected()) {
                //Change the characters to be readable
                passField.setEchoChar((char) 0);
            }
            else {
                //Change the characters to unreadable
                passField.setEchoChar('*');
            }
        }
    }
}
