//Package imports (Generated by IntelliJ)
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Arrays;


public class LoginFrame extends JFrame implements ActionListener {
    //Container that holds all the elements
    Container container = getContentPane();
    JLabel userLabel = new JLabel("Username");
    JLabel passLabel = new JLabel("Password");
    JTextField userTextField = new JTextField();
    JPasswordField passField = new JPasswordField();
    JButton loginButton = new JButton("Log in");
    JButton resetButton = new JButton("Reset");
    JCheckBox showPassword = new JCheckBox("Show Password");
    //Constructor
    LoginFrame() {
        setLayoutManager();
        setLocationAndSize();
        addComponentsToContainer();
        addActionEvent();
    }
    //Setting bounds manually, so don't need a layout manager
    public void setLayoutManager() {
        container.setLayout(null);
    }
    //Setting the bounds for all the elements
    public void setLocationAndSize() {
        //Username elements
        userLabel.setBounds(50,50,100,30);
        userTextField.setBounds(150,50,150,30);
        //Password elements
        passLabel.setBounds(50,100,100,30);
        passField.setBounds(150,100,150,30);
        passField.setEchoChar('*');
        //Other elements
        showPassword.setBounds(150,130,150,30);
        loginButton.setBounds(50,180,100,30);
        resetButton.setBounds(200,180,100,30);
    }
    //Adds all the components to the container
    public void addComponentsToContainer() {
        container.add(userLabel);
        container.add(passLabel);
        container.add(userTextField);
        container.add(passField);
        container.add(loginButton);
        container.add(resetButton);
        container.add(showPassword);
    }
    //Adds event listeners to the necessary elements
    public void addActionEvent() {
        loginButton.addActionListener(this);
        resetButton.addActionListener(this);
        showPassword.addActionListener(this);
    }
    @Override
    public void actionPerformed(ActionEvent actionEvent) {
        if (actionEvent.getSource() == loginButton) {
            String userText;
            String pwdText;
            userText = userTextField.getText();
            pwdText = passField.getText();
            try {
                if (UserData.getInstance().isLoginCorrect(userText, pwdText)) {
                    JOptionPane.showMessageDialog(this, "Correct Login");
                }
                else {
                    JOptionPane.showMessageDialog(this, "Incorrect Login");
                }
            } catch (InvalidKeySpecException e) {
                e.printStackTrace();
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            }
        }
        if (actionEvent.getSource() == resetButton) {
            userTextField.setText("");
            passField.setText("");
        }
        if (actionEvent.getSource() == showPassword) {
            if (showPassword.isSelected()) {
                passField.setEchoChar((char) 0);
            }
            else {
                passField.setEchoChar('*');
            }
        }
    }
}
